version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: insurance_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/logs:/app/app/logs
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: insurance_frontend
    command: streamlit run frontend.py --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16

    container_name: insu_db

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: 1234

      POSTGRES_DB: insu_premium
    
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
  
    