version: "3.8"

services:
  backend:
    build: .
    container_name: insurance_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: .
    container_name: insurance_frontend
    command: streamlit run app/frontend/frontend.py --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped